DROP TABLE AUTHOR IF EXISTS;

CREATE TABLE AUTHOR (
    ID INTEGER generated by default as identity (start with 1) not null,
    NAME varchar(40) not null,
    FIRST_NAME varchar(40) not null,
    MIDDLE_NAME varchar(40) not null,
    LAST_NAME varchar(50) not null
);